[book]
authors = ["giripriyadarshan"]
language = "en"
multilingual = false
src = "src"
title = "Servust"
description = "Rust multiple backend-server template generator"

[rust]
edition = "2021"

[output.html]
default-theme = "dark"
preferred-dark-theme = "navy"
copy-fonts = true
git-repository-url = "https://github.com/giripriyadarshan/servust"
git-repository-icon = "fa-github"
site-url = "/"
cname = "servust.giripriyadarshan.com"

[output.html.fold]
enable = false    # whether or not to enable section folding
level = 0         # the depth to start folding
