name: release

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: servust
            asset_name: servust-linux-amd64
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            artifact_name: servust
            asset_name: servust-apple-amd64
            target: x86_64-apple-darwin
          - os: windows-latest
            artifact_name: servust.exe
            asset_name: servust-windows-amd64.exe
            target: x86_64-pc-windows-msvc
          - os: ubuntu-latest
            artifact_name: servust
            asset_name: servust-linux-armv7
            target: armv7-unknown-linux-gnueabihf
          - os: macos-latest
            artifact_name: servust
            asset_name: servust-apple-arm64
            target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}