name: release

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: /home/runner/work/servust/servust/target/x86_64-unknown-linux-gnu/release/servust
            asset_name: servust-linux-amd64
            target: x86_64-unknown-linux-gnu
            install_dependencies: |
              sudo apt-get update
              sudo apt-get install -y libssl-dev
              export OPENSSL_DIR=/usr
          - os: macos-latest
            artifact_name: /Users/runner/work/servust/servust/target/x86_64-apple-darwin/release/servust
            asset_name: servust-apple-amd64
            target: x86_64-apple-darwin
            install_dependencies: |
              brew install openssl
              export OPENSSL_ROOT_DIR=/usr/local/opt/openssl
          - os: windows-latest
            artifact_name: D:\a\servust\servust\target\x86_64-pc-windows-msvc\release\servust.exe
            asset_name: servust-windows-amd64.exe
            target: x86_64-pc-windows-msvc
            install_dependencies: |
              choco install openssl
          # - os: ubuntu-latest
          #   artifact_name: servust
          #   asset_name: servust-linux-armv7
          #   target: armv7-unknown-linux-gnueabihf
          #   install_dependencies: |
          #     sudo apt-get update
          #     sudo apt-get install -y libssl-dev
          #     export OPENSSL_DIR=/usr
          # - os: macos-latest
          #   artifact_name: servust
          #   asset_name: servust-apple-arm64
          #   target: aarch64-apple-darwin
          #   install_dependencies: |
          #     brew install openssl
          #     export OPENSSL_ROOT_DIR=/usr/local/opt/openssl
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --release --target ${{ matrix.target }} --locked

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.artifact_name }}

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ github.token }}
          file: ${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          body: "Check out the [CHANGELOG](https://raw.githubusercontent.com/giripriyadarshan/servust/main/CHANGELOG.md)"
